language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "7"

matrix:
  fast_finish: true
  include:
    - node_js: "'lts/*'"
      env: LINT=true

script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -z "${LINT-}" ]; then npm run test-ci ; fi'

after_success: 'if [ -z "${LINT-}" ]; then npm run coverage ; fi'
