language: node_js
node_js:
  - "14"
  - "12"
  - "10"
cache:
  yarn: true
before_script: 'if [[ "$WEBPACK" != "default" ]]; then yarn add --dev webpack@${WEBPACK}; fi'
script: yarn test
env:
  - WEBPACK=default
  - WEBPACK=^5.0.0-0
jobs:
  include:
    - stage: codestyle
      node_js: "lts/*"
      script: yarn lint
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
