language: node_js
node_js:
  - "14"
  - "12"
  - "10"
cache:
  yarn: true
before_script: 'if [[ "$WEBPACK" != "default" ]]; then yarn add --dev webpack@^${WEBPACK}; fi'
script: yarn test
env:
  - WEBPACK=default
  - WEBPACK=5.0.0-0
matrix:
  include:
    - node_js: "lts/*"
      script: yarn lint
